## Linear Classifier in TensorFlow 
Using Low Level API in Eager Execution mode

In [97]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [0]:
import pandas as pd

In [0]:
data = pd.read_csv('/content/drive/My Drive/Lab/Iris.csv')

In [4]:
data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

### Load tensorflow

In [0]:
import tensorflow as tf

### Collect Data

In [0]:
from google.colab import drive
drive.mount('/gdrive')

In [0]:
import pandas as pd

In [0]:
data_prices = pd.read_csv('/content/drive/My Drive/Lab/prices.csv')

### Check all columns in the dataset

In [25]:
data_prices.columns

Index(['date', 'symbol', 'open', 'close', 'low', 'high', 'volume'], dtype='object')

### Drop columns `date` and  `symbol`

In [0]:
data_prices = data_prices.drop(['date','symbol'], axis=1)

In [27]:
data_prices.head()

         open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

### Consider only first 1000 rows in the dataset for building feature set and target set
Target 'Volume' has very high values. Divide 'Volume' by 1000,000

In [28]:
data_prices.shape

(851264, 5)

In [0]:
data_price1k = data_prices.head(1000)

In [33]:
data_price1k.shape

(1000, 5)

In [34]:
 data_price1k['volume'] = data_price1k['volume'] / 1000000

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [35]:
data_price1k.head()

         open       close         low        high  volume
0  123.430000  125.839996  122.309998  126.250000  2.1636
1  125.239998  119.980003  119.940002  125.540001  2.3864
2  116.379997  114.949997  114.930000  119.739998  2.4895
3  115.480003  116.620003  113.500000  117.440002  2.0063
4  117.010002  114.970001  114.089996  117.330002  1.4086

### Divide the data into train and test sets

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X = data_price1k.drop('volume', axis=1)
y = data_price1k['volume']

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

#### Convert Training and Test Data to numpy float32 arrays

In [40]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 700 entries, 731 to 37
Data columns (total 4 columns):
open     700 non-null float64
close    700 non-null float64
low      700 non-null float64
high     700 non-null float64
dtypes: float64(4)
memory usage: 27.3 KB

In [0]:
X_train = X_train.to_numpy('float32')
X_test =  X_test.to_numpy('float32')
y_train = y_train.to_numpy('float32')
y_test = y_test.to_numpy('float32')

In [52]:
type(X_test)

numpy.ndarray

### Normalize the data
You can use Normalizer from sklearn.preprocessing

In [0]:
from sklearn.preprocessing import Normalizer

#x_train_n = normalize(np.vstack([X_train]), norm='l2', axis=1)
#x_test_n = normalize(np.vstack([X_test]), norm='l2', axis=1)

In [0]:
transformer = Normalizer().fit(X_train)
X_train_new = transformer.transform(X_train)

In [0]:
transformer = Normalizer().fit(X_test)
X_test_new = transformer.transform(X_test)

## Building the Model in tensorflow

1.Define Weights and Bias, use tf.zeros to initialize weights and Bias

In [0]:
W = tf.Variable(tf.random_normal(shape=[4,1]), name="Weights")
b = tf.Variable(tf.zeros(shape=[1]),name="Bias")

In [94]:
W

2.Define a function to calculate prediction

In [0]:
y = tf.add(tf.matmul(X_train_new,W),b,name='output')

3.Loss (Cost) Function [Mean square error]

In [0]:
loss = tf.reduce_mean(tf.square(y-y_train),name='mse')

4.Function to train the Model

1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
train_op = tf.train.GradientDescentOptimizer(0.03).minimize(loss)

## Train the model for 100 epochs 
1. Observe the training loss at every iteration
2. Observe Train loss at every 5th iteration

In [0]:
#Input features
x = tf.placeholder(shape=[None,4],dtype=tf.float32, name='x-input')

#Normalize the data
x_n = tf.nn.l2_normalize(x,1)

#Actual Prices
y_ = tf.placeholder(shape=[None],dtype=tf.float32, name='y-input')

In [0]:
#Lets start graph Execution
sess = tf.Session()

# variables need to be initialized before we can use them
sess.run(tf.global_variables_initializer())

#how many times data need to be shown to model
training_epochs = 100

In [117]:
for epoch in range(training_epochs):
            
    #Calculate train_op and loss
    _, train_loss = sess.run([train_op,loss],feed_dict={x:X_train_new, y_:y_train})
    
    print ('Training loss at step: ', epoch, ' is ', train_loss)

Training loss at step:  0  is  225.87958
Training loss at step:  1  is  219.00435
Training loss at step:  2  is  213.68013
Training loss at step:  3  is  209.55702
Training loss at step:  4  is  206.36406
Training loss at step:  5  is  203.89143
Training loss at step:  6  is  201.97662
Training loss at step:  7  is  200.49374
Training loss at step:  8  is  199.34541
Training loss at step:  9  is  198.45616
Training loss at step:  10  is  197.76749
Training loss at step:  11  is  197.23419
Training loss at step:  12  is  196.82121
Training loss at step:  13  is  196.50139
Training loss at step:  14  is  196.25371
Training loss at step:  15  is  196.0619
Training loss at step:  16  is  195.9134
Training loss at step:  17  is  195.79837
Training loss at step:  18  is  195.70929
Training loss at step:  19  is  195.6403
Training loss at step:  20  is  195.58688
Training loss at step:  21  is  195.54553
Training loss at step:  22  is  195.51349
Training loss at step:  23  is  195.4887
Training loss at step:  24  is  195.46947
Training loss at step:  25  is  195.45459
Training loss at step:  26  is  195.44307
Training loss at step:  27  is  195.43416
Training loss at step:  28  is  195.42723
Training loss at step:  29  is  195.42188
Training loss at step:  30  is  195.41774
Training loss at step:  31  is  195.41454
Training loss at step:  32  is  195.41205
Training loss at step:  33  is  195.41013
Training loss at step:  34  is  195.40865
Training loss at step:  35  is  195.4075
Training loss at step:  36  is  195.4066
Training loss at step:  37  is  195.4059
Training loss at step:  38  is  195.40535
Training loss at step:  39  is  195.40494
Training loss at step:  40  is  195.40462
Training loss at step:  41  is  195.40437
Training loss at step:  42  is  195.40417
Training loss at step:  43  is  195.40402
Training loss at step:  44  is  195.40392
Training loss at step:  45  is  195.40382
Training loss at step:  46  is  195.40375
Training loss at step:  47  is  195.40369
Training loss at step:  48  is  195.40366
Training loss at step:  49  is  195.40363
Training loss at step:  50  is  195.4036
Training loss at step:  51  is  195.4036
Training loss at step:  52  is  195.40356
Training loss at step:  53  is  195.40356
Training loss at step:  54  is  195.40356
Training loss at step:  55  is  195.40355
Training loss at step:  56  is  195.40355
Training loss at step:  57  is  195.40355
Training loss at step:  58  is  195.40355
Training loss at step:  59  is  195.40353
Training loss at step:  60  is  195.40353
Training loss at step:  61  is  195.40355
Training loss at step:  62  is  195.40349
Training loss at step:  63  is  195.4035
Training loss at step:  64  is  195.40349
Training loss at step:  65  is  195.40355
Training loss at step:  66  is  195.40349
Training loss at step:  67  is  195.40353
Training loss at step:  68  is  195.40353
Training loss at step:  69  is  195.40353
Training loss at step:  70  is  195.40353
Training loss at step:  71  is  195.40353
Training loss at step:  72  is  195.40355
Training loss at step:  73  is  195.40353
Training loss at step:  74  is  195.40353
Training loss at step:  75  is  195.40353
Training loss at step:  76  is  195.40353
Training loss at step:  77  is  195.40353
Training loss at step:  78  is  195.40353
Training loss at step:  79  is  195.40353
Training loss at step:  80  is  195.40353
Training loss at step:  81  is  195.40353
Training loss at step:  82  is  195.40353
Training loss at step:  83  is  195.40355
Training loss at step:  84  is  195.40353
Training loss at step:  85  is  195.40353
Training loss at step:  86  is  195.40353
Training loss at step:  87  is  195.40353
Training loss at step:  88  is  195.40353
Training loss at step:  89  is  195.40355
Training loss at step:  90  is  195.40355
Training loss at step:  91  is  195.40355
Training loss at step:  92  is  195.40353
Training loss at step:  93  is  195.40353
Training loss at step:  94  is  195.40353
Training loss at step:  95  is  195.40353
Training loss at step:  96  is  195.40353
Training loss at step:  97  is  195.40355
Training loss at step:  98  is  195.40355
Training loss at step:  99  is  195.40353

In [118]:
print(sess.run(W))

[[-0.72241455]
 [-0.05216902]
 [-0.6659141 ]
 [ 0.5146053 ]]

In [0]:
sess.close()

In [0]:
#Lets start graph Execution
sess = tf.Session()

# variables need to be initialized before we can use them
sess.run(tf.global_variables_initializer())

#how many times data need to be shown to model
training_epochs = 100

In [121]:
#print training loss for every 5th iteration
for epoch in range(training_epochs):
            
    #Calculate train_op and loss
    _, train_loss = sess.run([train_op,loss],feed_dict={x:X_train_new, y_:y_train})
    
    if epoch % 5 == 0:
      print ('Training loss at step: ', epoch, ' is ', train_loss)

Training loss at step:  0  is  225.87958
Training loss at step:  5  is  203.89143
Training loss at step:  10  is  197.76749
Training loss at step:  15  is  196.0619
Training loss at step:  20  is  195.58688
Training loss at step:  25  is  195.45459
Training loss at step:  30  is  195.41774
Training loss at step:  35  is  195.4075
Training loss at step:  40  is  195.40462
Training loss at step:  45  is  195.40382
Training loss at step:  50  is  195.4036
Training loss at step:  55  is  195.40355
Training loss at step:  60  is  195.40353
Training loss at step:  65  is  195.40355
Training loss at step:  70  is  195.40353
Training loss at step:  75  is  195.40353
Training loss at step:  80  is  195.40353
Training loss at step:  85  is  195.40353
Training loss at step:  90  is  195.40355
Training loss at step:  95  is  195.40353

In [122]:
print(sess.run(W))

[[-1.0801225 ]
 [-0.30398908]
 [-0.6301103 ]
 [-0.12995513]]

In [123]:
print(sess.run(b))

[0.]

In [0]:
sess.close()

### Get the shapes and values of W and b

In [107]:
W

In [108]:
b

### Model Prediction on 1st Examples in Test Dataset

In [0]:
y_test_pred = tf.add(tf.matmul(X_test_new,W),b,name='output')

## Classification using tf.Keras

In this exercise, we will build a Deep Neural Network using tf.Keras. We will use Iris Dataset for this exercise.

### Load the given Iris data using pandas (Iris.csv)

In [0]:
data = pd.read_csv('/content/drive/My Drive/Lab/Iris.csv')

In [0]:
data = data.drop('Id',axis=1)

### Target set has different categories. So, Label encode them. And convert into one-hot vectors using get_dummies in pandas.

In [195]:
data.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [0]:
X = data.iloc[:,0:4].values
y = data.iloc[:,4].values

from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

Y = pd.get_dummies(y1).values

#from sklearn.model_selection import train_test_split
#X_train,X_test, y_train,y_test = train_test_split(X,y1,test_size=0.2,random_state=0)

### Splitting the data into feature set and target set

In [0]:
#done above

###  Building Model in tf.keras

Build a Linear Classifier model  <br>
1.  Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3<br> 
2. Apply Softmax on Dense Layer outputs <br>
3. Use SGD as Optimizer
4. Use categorical_crossentropy as loss function

In [0]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

In [0]:
model = Sequential()
model.add(Dense(12, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

### Model Training

In [200]:
model.fit(X,Y,epochs=100,batch_size=10)

Epoch 1/100
150/150 [==============================] - 0s 3ms/step - loss: 1.5018 - acc: 0.3333
Epoch 2/100
150/150 [==============================] - 0s 281us/step - loss: 1.1628 - acc: 0.3333
Epoch 3/100
150/150 [==============================] - 0s 276us/step - loss: 1.0875 - acc: 0.3333
Epoch 4/100
150/150 [==============================] - 0s 287us/step - loss: 1.0363 - acc: 0.3333
Epoch 5/100
150/150 [==============================] - 0s 235us/step - loss: 0.9974 - acc: 0.3333
Epoch 6/100
150/150 [==============================] - 0s 259us/step - loss: 0.9627 - acc: 0.3333
Epoch 7/100
150/150 [==============================] - 0s 326us/step - loss: 0.9302 - acc: 0.3333
Epoch 8/100
150/150 [==============================] - 0s 255us/step - loss: 0.9015 - acc: 0.3867
Epoch 9/100
150/150 [==============================] - 0s 245us/step - loss: 0.8761 - acc: 0.6000
Epoch 10/100
150/150 [==============================] - 0s 260us/step - loss: 0.8506 - acc: 0.6600
Epoch 11/100
150/150 [==============================] - 0s 259us/step - loss: 0.8250 - acc: 0.6600
Epoch 12/100
150/150 [==============================] - 0s 259us/step - loss: 0.8050 - acc: 0.6667
Epoch 13/100
150/150 [==============================] - 0s 255us/step - loss: 0.7833 - acc: 0.6667
Epoch 14/100
150/150 [==============================] - 0s 272us/step - loss: 0.7640 - acc: 0.6667
Epoch 15/100
150/150 [==============================] - 0s 268us/step - loss: 0.7441 - acc: 0.6667
Epoch 16/100
150/150 [==============================] - 0s 231us/step - loss: 0.7254 - acc: 0.6733
Epoch 17/100
150/150 [==============================] - 0s 260us/step - loss: 0.7056 - acc: 0.6667
Epoch 18/100
150/150 [==============================] - 0s 257us/step - loss: 0.6846 - acc: 0.6667
Epoch 19/100
150/150 [==============================] - 0s 259us/step - loss: 0.6658 - acc: 0.6800
Epoch 20/100
150/150 [==============================] - 0s 249us/step - loss: 0.6468 - acc: 0.6933
Epoch 21/100
150/150 [==============================] - 0s 251us/step - loss: 0.6293 - acc: 0.6733
Epoch 22/100
150/150 [==============================] - 0s 269us/step - loss: 0.6121 - acc: 0.7067
Epoch 23/100
150/150 [==============================] - 0s 262us/step - loss: 0.5950 - acc: 0.6800
Epoch 24/100
150/150 [==============================] - 0s 291us/step - loss: 0.5811 - acc: 0.8400
Epoch 25/100
150/150 [==============================] - 0s 253us/step - loss: 0.5676 - acc: 0.6867
Epoch 26/100
150/150 [==============================] - 0s 269us/step - loss: 0.5530 - acc: 0.7333
Epoch 27/100
150/150 [==============================] - 0s 241us/step - loss: 0.5435 - acc: 0.7800
Epoch 28/100
150/150 [==============================] - 0s 270us/step - loss: 0.5294 - acc: 0.7667
Epoch 29/100
150/150 [==============================] - 0s 262us/step - loss: 0.5206 - acc: 0.7600
Epoch 30/100
150/150 [==============================] - 0s 276us/step - loss: 0.5111 - acc: 0.8133
Epoch 31/100
150/150 [==============================] - 0s 247us/step - loss: 0.5044 - acc: 0.7800
Epoch 32/100
150/150 [==============================] - 0s 361us/step - loss: 0.4957 - acc: 0.8400
Epoch 33/100
150/150 [==============================] - 0s 249us/step - loss: 0.4875 - acc: 0.8333
Epoch 34/100
150/150 [==============================] - 0s 251us/step - loss: 0.4787 - acc: 0.7733
Epoch 35/100
150/150 [==============================] - 0s 238us/step - loss: 0.4750 - acc: 0.8267
Epoch 36/100
150/150 [==============================] - 0s 278us/step - loss: 0.4624 - acc: 0.8733
Epoch 37/100
150/150 [==============================] - 0s 256us/step - loss: 0.4611 - acc: 0.7933
Epoch 38/100
150/150 [==============================] - 0s 286us/step - loss: 0.4547 - acc: 0.8400
Epoch 39/100
150/150 [==============================] - 0s 259us/step - loss: 0.4458 - acc: 0.7733
Epoch 40/100
150/150 [==============================] - 0s 244us/step - loss: 0.4438 - acc: 0.8667
Epoch 41/100
150/150 [==============================] - 0s 240us/step - loss: 0.4372 - acc: 0.8533
Epoch 42/100
150/150 [==============================] - 0s 246us/step - loss: 0.4309 - acc: 0.8733
Epoch 43/100
150/150 [==============================] - 0s 248us/step - loss: 0.4262 - acc: 0.9067
Epoch 44/100
150/150 [==============================] - 0s 252us/step - loss: 0.4169 - acc: 0.9000
Epoch 45/100
150/150 [==============================] - 0s 239us/step - loss: 0.4137 - acc: 0.8667
Epoch 46/100
150/150 [==============================] - 0s 243us/step - loss: 0.4003 - acc: 0.8467
Epoch 47/100
150/150 [==============================] - 0s 248us/step - loss: 0.4059 - acc: 0.9067
Epoch 48/100
150/150 [==============================] - 0s 266us/step - loss: 0.3965 - acc: 0.9333
Epoch 49/100
150/150 [==============================] - 0s 272us/step - loss: 0.3968 - acc: 0.9067
Epoch 50/100
150/150 [==============================] - 0s 253us/step - loss: 0.3910 - acc: 0.9333
Epoch 51/100
150/150 [==============================] - 0s 256us/step - loss: 0.3841 - acc: 0.9400
Epoch 52/100
150/150 [==============================] - 0s 264us/step - loss: 0.3798 - acc: 0.9200
Epoch 53/100
150/150 [==============================] - 0s 240us/step - loss: 0.3715 - acc: 0.9333
Epoch 54/100
150/150 [==============================] - 0s 259us/step - loss: 0.3702 - acc: 0.9333
Epoch 55/100
150/150 [==============================] - 0s 257us/step - loss: 0.3632 - acc: 0.9467
Epoch 56/100
150/150 [==============================] - 0s 253us/step - loss: 0.3606 - acc: 0.9400
Epoch 57/100
150/150 [==============================] - 0s 257us/step - loss: 0.3533 - acc: 0.9533
Epoch 58/100
150/150 [==============================] - 0s 323us/step - loss: 0.3483 - acc: 0.9600
Epoch 59/100
150/150 [==============================] - 0s 253us/step - loss: 0.3446 - acc: 0.9267
Epoch 60/100
150/150 [==============================] - 0s 258us/step - loss: 0.3411 - acc: 0.9467
Epoch 61/100
150/150 [==============================] - 0s 264us/step - loss: 0.3359 - acc: 0.9600
Epoch 62/100
150/150 [==============================] - 0s 245us/step - loss: 0.3326 - acc: 0.9600
Epoch 63/100
150/150 [==============================] - 0s 241us/step - loss: 0.3303 - acc: 0.9333
Epoch 64/100
150/150 [==============================] - 0s 261us/step - loss: 0.3233 - acc: 0.9667
Epoch 65/100
150/150 [==============================] - 0s 255us/step - loss: 0.3243 - acc: 0.9467
Epoch 66/100
150/150 [==============================] - 0s 257us/step - loss: 0.3104 - acc: 0.9667
Epoch 67/100
150/150 [==============================] - 0s 245us/step - loss: 0.3076 - acc: 0.9400
Epoch 68/100
150/150 [==============================] - 0s 236us/step - loss: 0.3077 - acc: 0.9333
Epoch 69/100
150/150 [==============================] - 0s 246us/step - loss: 0.3033 - acc: 0.9667
Epoch 70/100
150/150 [==============================] - 0s 241us/step - loss: 0.3043 - acc: 0.9200
Epoch 71/100
150/150 [==============================] - 0s 258us/step - loss: 0.2900 - acc: 0.9600
Epoch 72/100
150/150 [==============================] - 0s 263us/step - loss: 0.2984 - acc: 0.9533
Epoch 73/100
150/150 [==============================] - 0s 247us/step - loss: 0.2905 - acc: 0.9733
Epoch 74/100
150/150 [==============================] - 0s 245us/step - loss: 0.2876 - acc: 0.9533
Epoch 75/100
150/150 [==============================] - 0s 241us/step - loss: 0.2829 - acc: 0.9333
Epoch 76/100
150/150 [==============================] - 0s 244us/step - loss: 0.2671 - acc: 0.9733
Epoch 77/100
150/150 [==============================] - 0s 243us/step - loss: 0.2707 - acc: 0.9600
Epoch 78/100
150/150 [==============================] - 0s 237us/step - loss: 0.2637 - acc: 0.9533
Epoch 79/100
150/150 [==============================] - 0s 238us/step - loss: 0.2644 - acc: 0.9533
Epoch 80/100
150/150 [==============================] - 0s 242us/step - loss: 0.2628 - acc: 0.9467
Epoch 81/100
150/150 [==============================] - 0s 239us/step - loss: 0.2516 - acc: 0.9667
Epoch 82/100
150/150 [==============================] - 0s 257us/step - loss: 0.2505 - acc: 0.9533
Epoch 83/100
150/150 [==============================] - 0s 269us/step - loss: 0.2533 - acc: 0.9333
Epoch 84/100
150/150 [==============================] - 0s 343us/step - loss: 0.2453 - acc: 0.9533
Epoch 85/100
150/150 [==============================] - 0s 256us/step - loss: 0.2394 - acc: 0.9733
Epoch 86/100
150/150 [==============================] - 0s 229us/step - loss: 0.2416 - acc: 0.9467
Epoch 87/100
150/150 [==============================] - 0s 254us/step - loss: 0.2370 - acc: 0.9600
Epoch 88/100
150/150 [==============================] - 0s 264us/step - loss: 0.2365 - acc: 0.9467
Epoch 89/100
150/150 [==============================] - 0s 252us/step - loss: 0.2380 - acc: 0.9400
Epoch 90/100
150/150 [==============================] - 0s 269us/step - loss: 0.2236 - acc: 0.9600
Epoch 91/100
150/150 [==============================] - 0s 261us/step - loss: 0.2291 - acc: 0.9667
Epoch 92/100
150/150 [==============================] - 0s 274us/step - loss: 0.2219 - acc: 0.9733
Epoch 93/100
150/150 [==============================] - 0s 249us/step - loss: 0.2158 - acc: 0.9667
Epoch 94/100
150/150 [==============================] - 0s 286us/step - loss: 0.2161 - acc: 0.9733
Epoch 95/100
150/150 [==============================] - 0s 251us/step - loss: 0.2106 - acc: 0.9600
Epoch 96/100
150/150 [==============================] - 0s 257us/step - loss: 0.2111 - acc: 0.9667
Epoch 97/100
150/150 [==============================] - 0s 260us/step - loss: 0.2074 - acc: 0.9667
Epoch 98/100
150/150 [==============================] - 0s 243us/step - loss: 0.2019 - acc: 0.9667
Epoch 99/100
150/150 [==============================] - 0s 277us/step - loss: 0.2028 - acc: 0.9667
Epoch 100/100
150/150 [==============================] - 0s 256us/step - loss: 0.1858 - acc: 0.9600

### Model Prediction

In [201]:
model.evaluate(X,Y)

150/150 [==============================] - 0s 448us/step

[0.23126144955555597, 0.9]

### Save the Model

In [0]:
import pickle
pickle.dump(model, open("model.pkl","wb" , ))
#loading a model from a file called model.pkl
model = pickle.load(open("model.pkl", "rb"))
##"rb" : this means read mode

### Build and Train a Deep Neural network with 2 hidden layer  - Optional - For Practice

Does it perform better than Linear Classifier? What could be the reason for difference in performance?